### PR TITLE
Add 8 variables to target by AGI range and remove corresponding aggregate targets

### PR DESCRIPTION
**Pull request by donboyd5**
Please see the three comments about the PR, below.

I would appreciate review by @martinholmer and @nikhilwoodruff .

This is my first-ever nontrivial pull request so if I should do something else please say so.

### CODE REVIEW

**Comment by donboyd5** [comment]
This is the first of 3 comments about this commit, which is the sole commit in the PR.

This PR adds 7 specific variables to by-agi-range targeting for 2021 and removes them from aggregate targeting (as the agi ranges add up to the total):

- business_net_profits
- capital_gains_gross
- ordinary_dividends
- partnership_and_s_corp_income
- taxable_interest_income      
- total_pension_income
- total_social_security    

The reason for choosing these 7 variables is that (1) they are important to the overall calculation of AGI, (2) some of them are substantially off from IRS values in individual income ranges, (3) they include some variables that tend to be concentrated in high income ranges, such as capital_gains_gross, and some that tend to be concentrated in much lower income ranges, such as total_social_security, and (4) they are likely to be relevant to some desired policy analyses. The goal is to substantially improve the characteristics of our data file so that it is likely to be useful for a broader range of reforms than included in our tests while being reasonably parsimonious in choice of targets, given the impact of additional targets on the time for reweighting optimization.

While not shown here, I added these targets in steps, one variable at a time, to see how the results changed.

I provide two sets of results in the next two comments (1) the tax-expenditure analysis requested in issue # 146, which is an analysis of final outputs, and (2) a brief discussion of impacts on file fidelity, relative to IRS 2021 published data, and a link to an extensive comparison. My conclusions are that (1) it has minimal impact on tax-expenditure estimates, and the changes appear to be approximately neutral relative to the existing master, and (2) the impacts on file fidelity are almost uniformly positive, albeit generally not huge in must income ranges, but substantial in some. I conclude that overall, this is a meaningful improvement to an already good data file.

**Comment by donboyd5** [comment]
Here is the diff versus tax_expenditures_master, with a little spacing added to improve readability. The differences appear to be minor to me, and often in the direction of federal agency estimates although I have not tried to conclude whether overall they are closer to agencies or not:

(tmd) tax-microdata-benchmarking$ diff tax_microdata_benchmarking/storage/output/tax_expenditures  tax_expenditures_master

**This commit:**
< YR,KIND,EST= 2023 iitax 2211.4
< YR,KIND,EST= 2023 ctc 129.4
< YR,KIND,EST= 2023 eitc 75.9
< YR,KIND,EST= 2023 social_security_partial_taxability 53.3
< YR,KIND,EST= 2023 niit -57.0
< YR,KIND,EST= 2023 cgqd_tax_preference 233.9
< YR,KIND,EST= 2023 qbid 55.3
< YR,KIND,EST= 2023 salt 20.8

< YR,KIND,EST= 2026 iitax 2784.9
< YR,KIND,EST= 2026 ctc 46.8
< YR,KIND,EST= 2026 eitc 84.9
< YR,KIND,EST= 2026 social_security_partial_taxability 72.3
< YR,KIND,EST= 2026 niit -55.1
< YR,KIND,EST= 2026 cgqd_tax_preference 231.9
< YR,KIND,EST= 2026 salt 162.7

**Master:**
> YR,KIND,EST= 2023 iitax 2215.0
> YR,KIND,EST= 2023 ctc 132.2
> YR,KIND,EST= 2023 eitc 78.6
> YR,KIND,EST= 2023 social_security_partial_taxability 52.2
> YR,KIND,EST= 2023 niit -52.9
> YR,KIND,EST= 2023 cgqd_tax_preference 221.7
> YR,KIND,EST= 2023 qbid 54.1
> YR,KIND,EST= 2023 salt 20.4

> YR,KIND,EST= 2026 iitax 2786.5
> YR,KIND,EST= 2026 ctc 48.6
> YR,KIND,EST= 2026 eitc 88.0
> YR,KIND,EST= 2026 social_security_partial_taxability 70.9
> YR,KIND,EST= 2026 niit -51.2
> YR,KIND,EST= 2026 cgqd_tax_preference 222.0
> YR,KIND,EST= 2026 salt 160.5

(tmd) tax-microdata-benchmarking$

**Comment by donboyd5** [comment]
[This link](https://tmd-compare.netlify.app/tmd.html#examine-datatable) is for a datatable that compares three 2021 data files to IRS published statistics for 2021. You can play with the dropdown boxes to see many more comparisons than noted here:

-  taxdata -- the default taxdata for 2021 -- based on puf.csv (developed from puf2011.csv), grown by tax-calculator to 2021 using taxdata and tax-calculator default assumptions
- pr150 -- data based on pr150, which was the current master when I prepared the master data, and is the same as what would be generated by the current master based on pr151
- pr151_bnpcggodpsitiitpitss -- data based on this pull request -- pr151 plus business net profits (bnp), capital gains gross (cgg), ordinary dividends (od), partnership and s-corp income (psi), taxable interest income (tii), total pension income (tpi), and total social security income (tss)

Amounts are in $ billions. A few notable results below.

It is moderately closer to total agi than PR 150 (equivalent to PR 151):
image

Because both PR 150 and pr151_bnpcggodpsitiitpitss target agi by agi range, there aren't any meaningful differences by agi range.

It's quite a bit better than PR 150 by AGI range for the newly range-targeted variables. For example, here is e00900 (business net profits) for two ranges. The headers for the 4 numeric columns are IRS target, value for the file in question, our file minus the target, and the difference as a percentage of the target:

image

Here are a few more ranges where again, the new file is closer to the IRS than PR 150:

image

Here are a few income ranges for total social security, where again the proposed file is closer to the IRS:

image

Finally, when we look at taxable income, the proposed file is generally closer to the IRS than PR 150, although not dramatically so or uniformly so:

About $37b closer in aggregate:

image

Generally closer in a lot of income ranges:
image

Although a little further away in the highest income range:
image

Still, overall an improvement in my opinion and likely to do better than PR 150 on reforms we have not estimated.

**Comment by martinholmer** [comment]
@donboyd5,
(1) You need to fix your pull request so that the tests pass.
(2) and do not put the two tax_expenditure* files under version control.

**Comment by donboyd5** [comment]
> @donboyd5, (1) you need to fix your pull request so that the tests pass, and (2) do not put the two tax_expenditure* files under version control.

Thanks. I can't do tonight but will try to figure out item 1 in the morning early. I tried to fix the linting one, and it said fine locally, but didn't work on GH. I'll try to figure out what I did wrong in morning. The test error is "AssertionError: Release tmd-prerequisites not found. Available releases: {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest', 'status': '401'}
make: *** [Makefile:3: install] Error 1" which I will try to figure out in morning also. tax_expenditure* problem will be easy.

**Comment by martinholmer** [comment]
@donboyd5,  Why didn't you move `qualified_dividends` from the aggregate to by-AGI category (the way you moved the `ordinary_dividends` variable)?

**Comment by donboyd5** [comment]
Sorry I did not try that. I wasn't sure whether ordinary dividends would be
sufficient. I'll look at how we did by AGI range in the link I put in the
comments. If we didn't do well perhaps we should move qualified dividends
in also.

**Comment by donboyd5** [comment]
I just checked. I don't have e00650 in my data table. I'll put it in the
morning and take a look.

**Comment by martinholmer** [comment]
@donboyd5 said:
 I wasn't sure whether ordinary dividends would be
sufficient. I'll look at how we did by AGI range in the link I put in the
comments. If we didn't do well perhaps we should move qualified dividends
in also.

Only `qualified_dividends` are taxed a lower rates (like long-term capital gains), so it is important to get them correct by AGI group.

**Pull request closed without merging**
