### PR TITLE
Remove negative weights and aggregate records

### LINKED ISSUE #97: Aggregate records are included in the tmd output files
@nikhilwoodruff could you please remove the 4 aggregate records from the various tmd files (the analysis below is based on tmd_2021.csv), and think about the potential issues noted below? Thanks. FYI, @martinholmer.

Here is what the 2015 PUF documentation (p.3) says about aggregate records:

image

I had raised concerns about the importance of these records - capital gains, in particular, are disproportionately large on one of these records – and said that I think we should explore in the future whether there is information in these 4 records that we can use. However, for purposes of the current project we agreed - as other modelers using previous PUFs had done - that the proper and conservative approach for now is to exclude these records from our tmd files. We can revisit in the future whether there are ways we can use information from these records to improve upon our simple rule of excluding them.

However, these 4 records nonetheless appear to be in our tmd files. The table below shows, for tmd_2021.csv:

- RECID for the 4 aggregate records
- tmd values in 2021 for s006 (our final weight), c00100 (AGI, calculated), c01000 (net capital gains, calculated), and taxbc (tax before credits), each with _tmd suffix,
- weighted values for the tmd c00100 and c01000 variables, with wtd_ prefix (weighted by s006_tmd)
- raw puf values in 2015 for e00100 (AGI) and e00100 (net capital gains), with _puf sufix
- I do not show original puf weights or pre-optimization tmd weights because the changes were not significant enough to be concerning.

image

A few observations:

- First and foremost, we don’t want the 4 aggregate records in our output file and should remove them.
- The extraordinary nature of these records is worth remembering: for example, RECID 999999 has average AGI of $369.3 million, and weighted capital gains are $111 billion (out of about $2 trillion).
- That certainly means these 4 records will have thrown off our optimized reweighting significantly and it will be important to see how things change after we remove them.
- Strange things have happened to these records as we moved from the raw 2015 puf to the extrapolated (uprated), reweighted tmd file for 2021. For example, raw 2015 AGI (e00100) on RECID 999996 changed from -$96.4 million to calculated AGI in 2021 of $11.1 million. That may be just fine - it may be Tax-Calculator doing what it should be doing. We don’t have to worry about it for these records but we do need to ask ourselves whether it suggests anything strange is going on that we should worry about for the other 225k records we have. I don’t have anything particular I’m worried about, it’s just an observation that I think we need to think about.

Seems like it would be a good idea to have a test for whether aggregate records are in the output files.

### LINKED ISSUE #98: Negative final weights in tmd files
@nikhilwoodruff, could you please make sure weight optimization cannot result in negative weights? @martinholmer, FYI.

On tmd_2021.csv, we have 2,012 records on which s006 is negative. No records have negative s006_original, the weight immediately before optimized reweighting. Thus, the optimization is causing this.

The negative-s006 records represent 84.5 thousand tax returns and result in weighted tax before credits of negative $1.7 billion. We had agreed to make sure optimized weights could not be negative and I thought had accomplished that for a while.

image

Seems like it would be a good idea to have a test for this.

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
Fixes #97 
Fixes #98 

Also adds a negative weight check.

### CODE REVIEW

**Comment by nikhilwoodruff** [comment]
@donboyd5- this PR is functional but just breaks one of the Tax Expenditure tests. If it's not a hassle I'd recommend checking out this branch in the meantime before I fix it over the weekend.

**Comment by donboyd5** [comment]
Perfect, will do. Thanks!

Don

**Comment by nikhilwoodruff** [comment]
Still a bit puzzled why the solver fails here. Here's my local output:

```console
Optimising weights: 100%|███████████████████| 2000/2000 [01:48<00:00, 18.42it/s]
...reweighting finished
>C weights all,puf,cps (#M)= 199.465 161.269 38.196
>C weights all_min,all_max (#)= 0.1 18196.9
>C W2_wages min,max ($)= 0 32778369
>C total weighted W2_wages ($B)= 374.478
>C total weighted QBID ($B)= 184.289
Total qbided amount:  184.28937322843296
Finding scale to use in imputing pass-through W-2 wages...
scale: 0.000000, dev: -98.394, tot: 107.406
scale: 1.000000, dev:   0.421, tot: 206.221
scale: 0.500000, dev:  -2.570, tot: 203.230
scale: 0.750000, dev:  -0.900, tot: 204.900
scale: 0.875000, dev:  -0.210, tot: 205.590
scale: 0.937500, dev:   0.111, tot: 205.911
scale: 0.906250, dev:  -0.048, tot: 205.752
scale: 0.921875, dev:   0.031, tot: 205.831
scale: 0.914062, dev:  -0.008, tot: 205.792
scale: 0.917969, dev:   0.012, tot: 205.812
scale: 0.916016, dev:   0.002, tot: 205.802
scale: 0.915039, dev:  -0.003, tot: 205.797
scale: 0.915527, dev:  -0.001, tot: 205.799
scale: 0.915771, dev:   0.000, tot: 205.800
scale: 0.915649, dev:  -0.000, tot: 205.800
scale: 0.915710, dev:   0.000, tot: 205.800
```

**Comment by donboyd5** [comment]
Screenshot far below is from my failed commit
300ca344f80fa641488716ba55ef92abd58130e2.

What this tells us is:

   - Order of events:
      - First, we combine puf and cps nonfilers and don't yet have qbid
      (not gone through tc), but we have w2 wages because, I assume,
we used the
      default ratio whatever that may be.
      - Then we go through tc and add qbid, which at 202.926, which is
      almost our target. Great.
      - Next we reweight. Aggregate weights have changed, but not
      dramatically. But W2 wages, which were calculated at the default scaling,
      with the new weight distribution, have fallen dramatically to $374.1 from
      $432.5.
      - This does NOT mean the new weights are adjusting actual wages of
      course, but rather they are adjusting the values of the 4
variables that go
      into qbi (e00900, e26270, e02100, e27200), which is multiplied by the
      default scaling to get passthrough w2 wages.
      - With the new much lower W2 wages the qbid deduction (qbided) has
      dropped dramatically, also, from $202.9 to $174.9
      - And we can see from the screenshot immediately below that there is
      no way to scale the dramatically lower wages to achieve the
known/reported
      qbid deduction. Acceptable scale values must be between 0 and 1 (probably
      in a much narrower range) but the [0,1] range can only get us qbided
      between $79 and $198 - not all the way up to $205.8.

[image: image.png]

There are a couple of possibilities:

   - Our QBI after reweighting may be way too low. Can we check published
   IRS stats for equivalents or rough equivalents to (e00900, e26270, e02100,
   e27200)? How did our weighted sums of each of these change with
   reweighting? Have they become implausible?
   - It's also possible that the relationship between w2 wages and qbi is
   far more complex than we assume. Nonlinear in ways that mean we can't get
   there with a linear scaling factor. I doubt that's the real cause but we
   could investigate if the reweighting is not the problem.  There would be no
   easy solution here.
   - Also, did we target qbided in the reweighting? I think we should. I'm
   guessing we didn't or we should have come close.





[image: image.png]

**Comment by donboyd5** [comment]
On the last three bullets:

* Looking into this
* Agree
* We are targeting four QBI SOI statistics: total QBI, filers with QBI, total QBI among taxable returns, taxable filers with QBI.

**Comment by nikhilwoodruff** [comment]
This PR only passes by expanding the TE test tolerance to 100% from 70%.

**Pull request merged**
