### PR TITLE
Add and test create_area_weights.py script

### PR DESCRIPTION
**Pull request by martinholmer**
In addition to the `tmd/areas/create_area_weights.py` script, there is a temporary pseudo state target file `tmd/areas/targets/bb_targets.csv` for testing the script.   Early tests with only twelve targets show that all CPU cores are being used in the optimization of the weights and the optimization execution times are short.

This pull request started out using the `scipy.optimize.minimize('L-BFGS-B')` function, but then switched to the `scipy.optimize.lsq_linear` function at the suggestion of Don Boyd.  Using `lsq_linear`, we have added the option to optimize the weights or optimize the weight ratios, again at the suggestion of Don Boyd.

Fixes issue #185.

### CODE REVIEW

**Comment by martinholmer** [comment]
With just two targets and the full TMD sample, we have these preliminary results:
```
POP0= 33.418
AGI0= 1481.418

RUNNING THE L-BFGS-B CODE
Machine precision = 2.220D-16
 N =       225256     M =           10
...[snip]...
At iterate    0    f=  1.67992D-03    |proj g|=  1.09165D-05
At iterate    1    f=  1.67983D-03    |proj g|=  1.09163D-05
...
At iterate   35    f=  2.83663D-10    |proj g|=  2.78498D-09
At iterate   36    f=  1.95115D-10    |proj g|=  1.88800D-09
           * * *
Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value
           * * *
   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
*****     36     38   8036     0 27733   1.888D-09   1.951D-10
  F =   1.9511503523972351E-010

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH             
>>> scipy.minimize exectime(secs)= 2.755
>>> scipy.minimize results:
   message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 1.951150352397235e-10
        x: [ 1.108e+02  1.091e+02 ...  2.637e+01  2.297e+01]
      nit: 36
      jac: [ 5.547e-13  5.407e-13 ...  5.202e-13  1.040e-12]
     nfev: 38
     njev: 38
 hess_inv: <225256x225256 LbfgsInvHessProduct with dtype=float64>

POP1= 33.002        <<< TARGET is 33.0
AGI1= 1402.228.     <<< TARGET is 1400.0
```

**Comment by donboyd5** [comment]
@martinholmer thank you for this. I am away through Thursday night, and am not yet set up to run tmd revisions on my computer with debugging (to step through line by line). I'll get to that point but might be a week or so due to other things going on. So my comments below are based just at looking at the code:

- From a technical perspective everything looks good to me, and is very cool. I have used scipy.minimize() and related functions extensively before but not much with Jax, which is essential with this problem.
- Thank you for adding `agilo` and `agihi`. Per email, **right**=False, which your implementation does, is consistent with all of the IRS reporting I have seen and is the best way to do it for all binning.
- I take it `initial_weights_scale` is intended to scale pre-optimization weights so that their sum approximately equals the expected sum for the area in question.
- It might be good to add to your pre- and post- optimization printing the sum of unscaled weights and (more important) the sum of scaled weights.
- Might be nice to have a feature you can turn on that prints or writes to a file for each target certain diagnostic information: the target, pre-optimization scaled-weighted total, post-optimization scaled-weighted total, % difference pre- vs. target, % difference post- vs. target. The % diff pre- vs. target can help identify bad targets or targets that will be especially hard to hit, and the % diff post vs. target shows how well we did. It also could be worth printing summary stats such as max % diffs (in case we have hundreds of targets and don't want to sift through them all. Or perhaps just write a csv file that allows post-run diagnostics if we want.
- Just an observation, not a concern: I was surprised that minimize() declared success with AGI1= 1402.228, which is 0.16% above the target. Not a concern because of course we'd be pleased if every targeted variable comes within 1% of the target, much less 0.16%. But a surprise because we have something like 225k weights to adjust to hit 2 targets so obviously it would be easy to hit the targets within 0.0000000001% or something like that. So it's worth keeping an eye on stopping criteria, for possible adjustment, as we add many targets.
- It would be good to have diagnostics on weight changes - for example the distribution (quantiles) of res.x or of res.x / wght.
- I like the objective function (mean square relative difference vs. targets). We may want to consider whether to incorporate changes in weights in the objective function. This is a stickier question for subnational weighting than for national weighting. For the nation, it is important because there really should be information in the IRS weights and if our optimization changes them dramatically that is a yellow flag and possibly a red flag because they may throw other things off. But for subnational areas, we expect the distribution to be dramatically different - NY has far more multi-millionaires with income related to financial markets than does Mississippi and we'd expect weights to be dramatically different from national averages so large weight changes aren't necessarily a yellow flag or red flat.

**Comment by donboyd5** [comment]
@martinholmer I have a concern about the precision of minimize() calculations, coupled with our objective function. It is an easily solved problem, I believe. Please see my follow-on note, with advice from ChatGPT-o.

The first screenshot below shows my calculations in [Google sheets](https://docs.google.com/spreadsheets/d/1DLH16IcogX9Dc_5adhHLVdLWt25FuaJDhVGfhbLGBl4/edit?usp=sharing) of the objective function at its initial value and at the optimal value. The second screenshot is the [summary output](https://github.com/PSLmodels/tax-microdata-benchmarking/pull/185#issuecomment-2325385577) from the optimization (I pulled some numbers from this output).

As you can see, my Google Sheets objective function calculation is quite close to the L-BFGS-B reported values at iteration 0 (the numbers in green), although still different. But at the purportedly optimal solution, they are very different (the numbers in red): I get 1.268**e-6** but L-BFGS-B reports 1.951**e-10**. I checked it in Excel, also, and on my HP-12C scientific calculator, which gave the same answer as Google sheets, which is very different from L-BFGS-B in minimize().

Which is correct, minimize() or the other 3 methods? I asked ChatGPT about precision, and it said 15 digits in Excel and Google Sheets, 13 digits in the HP-12C, and 15-17 digits in the minimize() implementation of L-BFGS-B, suggesting a win for minimize(). But I don't believe it.

So I found an arbitrary precision calculator at [Wolfram](https://www.wolframalpha.com/input?i=50+digits+of+%28square%2833.002+%2F+33.0+-1%29+%2B+square%281402.228+%2F+1400.0+-+1%29%29+%2F+2) and asked for 50 digits of precision at the reported optimal values. The result is the 3rd screenshot below.











image


image

image

**Comment by donboyd5** [comment]
As you can see, ChatGPT-o recommends scaling the objective function, dividing by a constant - the unscaled value at the starting point. Thus, its value will be 1 at iteration 0 (instead of about 1e-3 at the starting point). I have done this before; sometimes optimization software recommends scaling so that the initial objective function value is 100 or 1000. In any event, a small positive number generally seems to be good and help avoid roundoff error in calculations.

I think if you scale the objective function you will find that L-BFGS-B will perform better in many ways.

Before you do your own scaling, you might want to see if minimize() or L-BFGS-B has an option to make its own scaling decision - if so, it might do a better job than we would do. But if not, I think scaling the intial value to 1, 100, or 1000 should do the trick.

**Comment by donboyd5** [comment]
@Martin Holmer ***@***.***> many thanks. I made quite a few
comments for your consideration and, at some point, for discussion. However
the important comment, which I don't get to right away so please read the
later comments, pertains to precision and scaling. I think that will buy us
big improvements early, with little effort.

Thanks!

**Comment by martinholmer** [comment]
After the code changes made on Friday, Sep 6, we have the following results generated on an older iMac with four-Intel-CPU-cores for this arbitrary eight-target `zz_targets.csv` file:
```
varname,count,scope,agilo,agihi,fstatus,target
XTOT,       0,    0,-9e99, 9e99,      0,  33e6
c00100,     0,    1,-9e99, 9e99,      0,1200e9
XTOT,       1,    1,  1e6, 9e99,      0,   1e3
XTOT,       1,    1,    1, 30e3,      0,   7e6
e00200,     0,    1,-9e99, 9e99,      0,1000e9
e00300,     0,    1,-9e99, 9e99,      0,  20e9
e00900,     0,    1,-9e99, 9e99,      0,  30e9
e02000,     0,    1,-9e99, 9e99,      0,  30e9
```
The `python create_area_weights.py zz` command generates these results (where the population target on the second row of the `zz_targets.csv` file is used to scale the national weights to the specified area population before the weights optimization begins):
```
% python create_area_weights.py zz
NUMBER_OF_TARGETS = 8
TARGET01:ACT-EXP,ACT/EXP=  7.988215966e-06, 1.000
TARGET02:ACT-EXP,ACT/EXP=  2.172814207e-01, 1.217
TARGET03:ACT-EXP,ACT/EXP=  8.540735796e+01, 86.407
TARGET04:ACT-EXP,ACT/EXP= -2.249447702e-01, 0.775
TARGET05:ACT-EXP,ACT/EXP= -1.092980193e-01, 0.891
TARGET06:ACT-EXP,ACT/EXP= -4.890001192e-01, 0.511
TARGET07:ACT-EXP,ACT/EXP=  3.540924822e-01, 1.354
TARGET08:ACT-EXP,ACT/EXP=  2.195502846e+00, 3.196
US_PROPORTIONALLY_SCALED_LOSS_FUNCTION_VALUE= 7.299711286e+03
>>> scipy.minimize execution: 67.2 secs  iterations=1371  success=True
>>> scipy.minimize all results:
   message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 0.025723295286297798
        x: [ 1.347e+02  1.329e+02 ...  2.642e+01  2.343e+01]
      nit: 1371
      jac: [-1.914e-08 -1.953e-08 ...  5.023e-09  1.005e-08]
     nfev: 1430
     njev: 1430
 hess_inv: <225256x225256 LbfgsInvHessProduct with dtype=float64>
# units in total is 225256
# units with post weight equal to zero is 32867
# units with post/pre weight ratio > 2.0 is 20743
# units with post/pre weight ratio > 4.0 is 10570
# units with post/pre weight ratio > 6.0 is 7126
# units with post/pre weight ratio > 8.0 is 5870
TARGET01:ACT-EXP,ACT/EXP=  8.290515395e-02, 1.083
TARGET02:ACT-EXP,ACT/EXP=  1.044105017e-01, 1.104
TARGET03:ACT-EXP,ACT/EXP= -1.505569928e-04, 1.000
TARGET04:ACT-EXP,ACT/EXP= -8.799224794e-02, 0.912
TARGET05:ACT-EXP,ACT/EXP=  1.250444443e-02, 1.013
TARGET06:ACT-EXP,ACT/EXP= -6.943828846e-03, 0.993
TARGET07:ACT-EXP,ACT/EXP= -3.128561705e-03, 0.997
TARGET08:ACT-EXP,ACT/EXP= -2.878504539e-03, 0.997
AREA-OPTIMIZED_LOSS_FUNCTION_VALUE= 2.574012737e-02
```

**Comment by donboyd5** [comment]
Thanks, @martinholmer. I'm away today but here are a few quick thoughts:

- Your scaling seems to have solved the obvious roundoff problems -- that is, I can reproduce the reported loss values from the reported target results. 
- Still, I think we should keep roundoff error in mind. You have scaled the coefficient matrix rather than the objective function. Two thoughts there, if we decide we are running into roundoff issues (which can make solution inefficient): (1) we might want to experiment with scaling each target to a larger number than 1. After all, with each record being 1 / 225k of the total (setting aside weight differentials), the coefficients will be extremely small when they are influencing a target that is scaled to equal one. For example, we could scale them so that each target equals the anticipated population total. (2) we could scale the objective function.
- I wouldn't be surprised if larger targets got us better convergence -- CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH makes me wonder if we are unable to reduce the objective function much because it is so small.
- That third target is dominating everything. Let's hope that we don't have any real-world targets that are 86 times the size of a proportionately-scaled-weights target. If we do, we may want to deprioritize the target, either by dropping it, or having a scaling factor that makes it less important than the others. I think / hope it is the reason for the relatively poor results (off by as much as 10% -- although we nail the 3rd target). 
- Even though the gradient is easy to calculate here and you have simply code it rather than asked Jax to compute it, it would be interesting to see whether allowing / requiring Jax to compute the gradient got us any improvements.
- Perhaps it would be better conceptually to do the proportionate area scaling as the ratio of targeted xtot to wtd sum of xtot on the file (rather than to US pop) but I doubt it would make any difference - it would give us somewhat different starting values for wght.
- 67 seconds is a long time and 1,371 iterations is a lot of iterations for what should be a very easy problem - 8 targets. The difficulty the solver is having could be a result of (1) numerical problems (thus my comments about scaling)

**Pull request merged**
