### PR TITLE
Experimentation branch on SALT and weight deviation penalty

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
Double checking how we target SALT as per #126 - will post updates here.

### CODE REVIEW

**Comment by nikhilwoodruff** [comment]
- [ ] Check number of itemisers and standard deduction users

**Comment by martinholmer** [comment]
@nikhilwoodruff,  Be sure to **CHANGE SCALE FROM 0.20 TO 0.16** in your PR #130.

**Comment by martinholmer** [comment]
After adding the writing of a `storage/output/tax_expenditures` file, we can see the drastic effects on 2023 tax expenditures of changing the reweighting penalty from 0.0 to 0.2:

```
(taxcalc-dev) tax-microdata-benchmarking% diff junk02 junk00 
9c9
<   REWEIGHT_DEVIATION_PENALTY = 0.200
---
>   REWEIGHT_DEVIATION_PENALTY = 0.000
...
< >C weights all,puf,cps (#M)= 199.188 160.730 [160.8] 38.458
< >C weights all_min,all_max (#)= 1.1 9675.7
< >C weighted puf CTC ($B)= 248.696
< >C W2_wages min,max ($)= 0 41827177
< >C weighted puf W2_wages ($B)= 370.044
< >C weighted puf QBID ($B)= 241.702 [205.8]
---
> >C weights all,puf,cps (#M)= 199.886 161.428 [160.8] 38.458
> >C weights all_min,all_max (#)= 0.1 16564.3
> >C weighted puf CTC ($B)= 173.810
> >C W2_wages min,max ($)= 0 41827176
> >C weighted puf W2_wages ($B)= 280.495
> >C weighted puf QBID ($B)= 184.068 [205.8]
...
< YEAR,KIND,ESTIMATE= 2023 cg_tax_preference 128.6
< YEAR,KIND,ESTIMATE= 2023 ctc 143.3
< YEAR,KIND,ESTIMATE= 2023 eitc 86.0
< YEAR,KIND,ESTIMATE= 2023 niit -33.9
< YEAR,KIND,ESTIMATE= 2023 qbid 74.4
< YEAR,KIND,ESTIMATE= 2023 salt 7.3
< YEAR,KIND,ESTIMATE= 2023 social_security_partial_taxability 53.6
---
> YEAR,KIND,ESTIMATE= 2023 cg_tax_preference 228.5
> YEAR,KIND,ESTIMATE= 2023 ctc 94.3
> YEAR,KIND,ESTIMATE= 2023 eitc 77.8
> YEAR,KIND,ESTIMATE= 2023 niit -56.4
> YEAR,KIND,ESTIMATE= 2023 qbid 56.6
> YEAR,KIND,ESTIMATE= 2023 salt 12.0
> YEAR,KIND,ESTIMATE= 2023 social_security_partial_taxability 51.9
```

**Comment by nikhilwoodruff** [comment]
After some more investigation, I've found an issue with SALT and I think it's a bug in the reweighting process: we significantly (+190%) overestimate the SALT itemiser count, but hit the aggregate target (-3%). This explains the SALT tax expenditure estimate being too low- we're missing the high income filers (also verified with the distribution bounds: we hit the aggregates in lower AGI ranges but miss around half of high-income ranges).

**Comment by donboyd5** [comment]
Great. This is an important issue to discuss. Well worth some intellectual
effort.

**Comment by nikhilwoodruff** [comment]
I'll merge this when the tests pass

**Comment by martinholmer** [comment]
@nikhilwoodruff said in PR #130:
> I'll merge this when the tests pass.

**WAIT**.   Where is your proof that the 2023 tax expenditure estimates don't change?

**Comment by nikhilwoodruff** [comment]
Good point- will not merge if they do. I'll rerun the shell script

**Comment by martinholmer** [comment]
@nikhilwoodruff,  You also need to remove `qualified_business_income_deduction` from the list of targets in the `reweight.py` module.

**Comment by martinholmer** [comment]
@nikhilwoodruff,  Please remove this:
```
tax_microdata_benchmarking/examination/taxcalculator/move_tmd_from_outputs.py
```

**Comment by nikhilwoodruff** [comment]
@martinholmer could we keep it in? Unless there's an easier way I'm missing, I added a `make` command: `make tax-expenditures-report` that executes `runs.sh`

**Comment by martinholmer** [comment]
@nikhilwoodruff asked:
> could we keep it in? Unless there's an easier way I'm missing, I added a make command: make tax-expenditures-report that executes runs.sh

OK.

**Comment by nikhilwoodruff** [comment]
@martinholmer I've uploaded the new comparisons, which show SALT staying at 20bn

**Comment by martinholmer** [comment]
@nikhilwoodruff,   WHY are the `tmd-23.res-expect` and tmd-26.res-expect` changing?
That should not be happening.   Don't merge #130 until you can explain!

**Comment by nikhilwoodruff** [comment]
Holding off since this PR appears to move the CTC expenditure down to 96bn from 132bn

**Comment by martinholmer** [comment]
@nikhilwoodruff,  consider this Python API approach to `make tax-expenditures-report`

(1) Remove the Makefile target `tax_microdata_benchmarking/examination/taxcalculator/tmd.csv.zip`

(2) Remove the
`tax_microdata_benchmarking/examination/taxcalculator/move_tmd_from_outputs.py` module

(3) Change the Makefile target `tax-expenditures-report` to this:

tax-expenditures-report: flat-file
	TAXEXP=x pytest . -m taxexp
	cat tax_microdata_benchmarking/storage/output/tax_expenditures

Does this make sense to you?   
This approach is what I was suggesting during our team meeting on Wednesday.

**Comment by martinholmer** [comment]
@nikhilwoodruff,  You can reopen PR #130 if you want to do more work on it.

**Pull request closed without merging**
