### PR TITLE
Make file naming convention Windows-friendly

### PR DESCRIPTION
**Pull request by bristowrichards**
In `reweight.py`, the current TensorFlow log file name uses ISO date/time naming, which results in the `:` character used in the file placed in `storage\output\reweighting\`. The `:` character cannot be used in Windows machines to save files. This small pull request instead uses the `.` character. I don't believe it should cause any issues for TF but I may be mistaken.

### CODE REVIEW

**Comment by martinholmer** [comment]
@bristowrichards,  Could you continue to use the "T" character (instead of "_") in the time stamp?   If so, I'd be happy to merge your pull request.

**Comment by bristowrichards** [comment]
Sure thing! I can also change the `:` characters to `.` if it keeps it more human-readable, as in Option B below:

|   |   |
|---|---|
| Original ISO | `2021_2024-07-10T17:33:53` |
| My initial change | `2021_2024-07-10_13-51-20` |
| Option A | `2021_2024-07-10T13-51-20` |
| Option B | `2021_2024-07-10T13.51.20` |

**Comment by martinholmer** [comment]
@bristowrichards said in PR #132:
> I can also change the : characters to . if it keeps it more human-readable, as in Option B.

That is an excellent idea!   If you can implement Option B today, I'll merge your changes.
Thanks for the contribution.

**Comment by martinholmer** [comment]
@nikhilwoodruff, Are there any problems with the proposed change in the reweighting trace file naming convention being suggested in PR #132?

**Comment by bristowrichards** [comment]
@martinholmer @nikhilwoodruff 

Anything I need to change here?

**Comment by martinholmer** [comment]
@bristowrichards asked in PR #132:
> Anything I need to change here?

The code changes are fine.    But you need to make those code changes on a **branch** (not on master) and then submit that branch to github directly and not through your github clone of this repository.   So, it looks like you made your code changes on your local master branch and did this:
```
git push origin master
```
Instead put your code changes on a branch called `my-changes`, and then submit as follows:
```
git push upstream my-changes
```

**Comment by bristowrichards** [comment]
Closed this since I @martinholmer pointed out my PR mistake - thanks for flagging that! First time contributing to a project. I'll open a new PR with a properly-formatted branch with the feature change in the coming days.

**Pull request closed without merging**
