### PR TITLE
Move PUF creation to in-repo

### LINKED ISSUE #50: Add Tax-Expenditure benchmarks to automated tests

### LINKED ISSUE #63: Move PUF data file handling to this repo
Currently it's taken from PolicyEngine, but we should move to fully internal for independence. This doesn't affect the nature of the comparisons.

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
Fixes #63 
Fixes #50 

This PR also moves files into a more sensible structure, with clearer separation between datasets. It also adds a live dashboard with comparisons akin to Don's notebooks, plus the tax expenditure tests.

### CODE REVIEW

**Comment by martinholmer** [comment]
@nikhilwoodruff,   
Why is this PR removing the `test_create_taxcalc_tmd_file` test I recently added?
Please leave this test in!

**Comment by nikhilwoodruff** [comment]
> @nikhilwoodruff, Why is this PR removing the `test_create_taxcalc_tmd_file` test I recently added? Please leave this test in!

Thanks Martin- re-added (apologies, it must have been moved in the merge conflict).

**Comment by nikhilwoodruff** [comment]
I'm going to merge this pull request: it's passing tests (the last commit did not make any code changes).

**Comment by nikhilwoodruff** [comment]
A note to say that this moves the recently created create_taxcalc_* files one level down, into the `utils/` folder.

**Pull request merged**
