### PR TITLE
Create a clean base of R code from which to make new R-related pull requests

### PR DESCRIPTION
**Pull request by donboyd5**
Due to git and github naivete, my branches with R code became complex and unwieldy, per @martinholmer.

This PR has fairly clean current R code for two R projects: "prepare", for preparing targets, and "examine" for examining results.

My plan, unless advised otherwise, is to have the following workflow:

- continue R work locally, and periodically push a new branch to my fork for backup / tracking
- regularly push that working branch to this repo as a draft PR
- when I have a cohesive set of changes on a single topic that I think is ready for merging into master -- for example, add-filterable-results, create a local branch with that small cohesive set of changes and push it upstream for merging into master
- if I have work that would alter .py files rather than add / edit R-related files, create a separate PR for those edits and submit them early on

@martinholmer if there is a better workflow please advise

**NOTE:** This PR does not push *_targets.csv files. That will come in a future PR.

### CODE REVIEW

**Comment by martinholmer** [comment]
@donboyd5,  first thing to do is to resolve all the conflicts with the code in your earlier PRs.

**Comment by martinholmer** [comment]
@donboyd5,  why does PR #280 include many of my changes from two months ago?

**Comment by donboyd5** [comment]
Not sure why. I intended to base this pr on current master. I did git fetch upstream beforehand. If you have advice, great. I assume I should go back, make sure it is based on current master and try again?

**Comment by martinholmer** [comment]
@donboyd5 said in PR #280:
> I assume I should go back, make sure it is based on current master and try again?

That would be prudent.

**Comment by donboyd5** [comment]
I'm going to retry, from scratch.

**Pull request closed without merging**
