### PR TITLE
revert Census-year assumption to 2010 and revise associated comment

### PR DESCRIPTION
**Pull request by donboyd5**
Addresses #242

### CODE REVIEW

**Comment by martinholmer** [comment]
@donboyd5,  I don't know what is wrong with your PR #244.
Does [my yesterday suggestion](https://github.com/PSLmodels/tax-microdata-benchmarking/issues/242#issuecomment-2424047672) not work?

**Comment by donboyd5** [comment]
Thanks, @martinholmer. It does work, but I had already created a local branch that does what I need so I went with that. All good. Thanks for following up.

**Comment by donboyd5** [comment]
Eventually I'll figure out why I don't have the right permissions for the PUF for purposes of pull requests. I tried for an hour or two yesterday, getting advice from ChatGPT, but I still didn't figure it out. I'll work on it after Phase 4.

**Comment by martinholmer** [comment]
Proposed changes in this PR were included in merged PR #251.

**Pull request closed without merging**
